# Generated by Django 5.1.4 on 2025-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_imagetype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200, null=True)),
                ('ProductPrice', models.CharField(max_length=200, null=True)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='productImages/')),
            ],
        ),
    ]
