# Generated by Django 5.1.4 on 2025-03-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mainproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusTop', models.CharField(max_length=200, null=True)),
                ('StatusMiddle', models.CharField(max_length=200, null=True)),
                ('StatusBottom', models.CharField(max_length=200, null=True)),
                ('SlideImage', models.ImageField(blank=True, null=True, upload_to='productImages/')),
            ],
        ),
    ]
