# Generated by Django 5.1.4 on 2025-03-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FooterTitle', models.CharField(max_length=200, null=True)),
                ('FooterTextTop', models.CharField(max_length=200, null=True)),
                ('FooterTextMiddle', models.CharField(max_length=200, null=True)),
                ('FooterTextBottom', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
