# Generated by Django 5.1.4 on 2025-03-11 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sub_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubMenuName', models.CharField(max_length=200, null=True)),
                ('MenuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.menu')),
            ],
        ),
    ]
