# Generated by Django 5.1.4 on 2025-03-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_menu_sub_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutTitle', models.CharField(max_length=200, null=True)),
                ('AboutText', models.CharField(max_length=200, null=True)),
                ('AboutImage', models.ImageField(blank=True, null=True, upload_to='productImages/')),
            ],
        ),
    ]
