# Generated by Django 5.1.4 on 2025-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_aboutdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactTitle', models.CharField(max_length=200, null=True)),
                ('ContactDes', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
