# Generated by Django 5.1.4 on 2025-03-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_blogpro'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogTitle', models.CharField(max_length=200, null=True)),
                ('BlogImage', models.ImageField(blank=True, null=True, upload_to='productImages/')),
            ],
        ),
    ]
