# Generated by Django 5.1.4 on 2025-03-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_bloglocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutTitle', models.CharField(max_length=200, null=True)),
                ('AboutText', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogTitle', models.CharField(max_length=200, null=True)),
                ('BlogText', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fcontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactTitle', models.CharField(max_length=200, null=True)),
                ('ContactText', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fthank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThankTitle', models.CharField(max_length=200, null=True)),
                ('ThankText', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
